/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (2.0.3) or chardet (5.1.0) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/can/interfaces/socketcan/socketcan.py", line 792, in _send_once
    sent = self.socket.send(data)
OSError: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test5.py", line 64, in <module>
    main(debug=True)
  File "test5.py", line 55, in main
    send_can_message(bus, telemetry)
  File "test5.py", line 8, in send_can_message
    bus.send(message)
  File "/usr/local/lib/python3.8/dist-packages/can/interfaces/socketcan/socketcan.py", line 777, in send
    sent = self._send_once(data, channel)
  File "/usr/local/lib/python3.8/dist-packages/can/interfaces/socketcan/socketcan.py", line 794, in _send_once
    raise can.CanOperationError(
can.exceptions.CanOperationError: Failed to transmit: Invalid argument [Error Code 22]
SocketcanBus was not properly shut down
